const constants = {
  APP_NAME: 'Fitness App',
  HEADER: 'FIND OUT EXACTLY TRAINING WILL WORK SPECIFICALLY FOR YOU',
  USER_IN_USE_EMAIL_ERROR: 'Email address already in use',
  USER_INVALID_EMAIL_ERROR: 'Invalid email',
  USER_CREATE_ERROR: 'Something went wrong',
  NEXT: 'Next',
  SIGN_IN: 'Sign in',
  SIGN_UP: 'Sign up',
  BACK: 'Back',
  SAVE: 'Save',
  REGISTRATION_BUTTON_LABEL: "Don't have an account? Sign up now!",
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'Enter your email...',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: '*******',
  NAME_LABEL: 'Full name',
  NAME: 'name',
  NAME_PLACEHOLDER: 'Enter your name...',
  REGISTRATION_SUCCESS: 'You have successfully registered!',
  GENDER: 'Gender',
  AGE: 'Age',
  WEIGHT: 'Weight (kg)',
  HEIGHT: 'Height (cm)',
  ABOUT_YOU: 'What are your body measurements?',
  ABOUT_YOU_DESC: 'FILL OUT YOUR DATA',
  FITNESS_LEVEL: 'What is your level of fitness?',
  BEGINNER: 'Beginner',
  INTERMEDIATE: 'Intermediate',
  ADVANCED: 'Advanced',
  USERS_PATH: 'users',
};

export default constants;
